### ISSUE TITLE
Extract and clean-up stage 1 reference pages

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-child-latin#1]
* Dating Latin documents
* How to decline personal names
* Problems with Latin and the documents
* Bibliography

**Comment by grange85** [comment]
@ManassehBBTNA I think these resources are possibly straightforward content extracts - but the html will need to be cleaned up a little. The regular expression I used for removing unwanted attributes is here:
https://gist.github.com/grange85/7c6ccc8e532b5423c35bdf675457249a

**Comment by ManassehBBTNA** [comment]
Actually Andy, can I clean up the Word List first?

**Comment by grange85** [comment]
No problem @ManassehBBTNA - I've assigned that task to you now.

**Comment by ManassehBBTNA** [comment]
The Bibliography has been extracted, cleaned up and put on the feature/resource-content branch on tna-latin- tutorials repo- https://github.com/nationalarchives/tna-latin-tutorials/tree/feature/resource-content
