### ISSUE TITLE
Develop JS version of stage 1 - activity 01 (drag and drop)

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-child-latin#6]
You can see the existing version here:
http://www.nationalarchives.gov.uk/latin/beginners/activities/lesson01.htm

**Comment by grange85** [comment]
@Ash98 and @Urborging - I've assigned you both to this activity - not sure if you want to pair up but if you'd prefer to work separately let me know and I can pull maybe the "practice sentences" activity into the sprint - I was just a bit hesitant at overloading you!

**Comment by gtvj** [comment]
@Ash98 and @Urborging - please ensure you've considered and covered the accessibility needs for any activities. Let me know if you need any help with this.
